---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 25565, host: 25565, auto_correct: true}]
  customize:
    cpus: 4
    memory: 8096

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[minecraft-basic::default]
    attributes:
