name 'minecraft-basic'
maintainer 'JJ Asghar'
maintainer_email 'jj@chef.io'
license 'Apache v2'
description 'Installs/Configures minecraft server'
long_description 'Installs/Configures minecraft server'
version '1.0.0'
