name 'minecraft-basic'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures minecraft-basic'
long_description 'Installs/Configures minecraft-basic'
version '0.1.0'
